server:
 port: 8081

spring:
 application:
  name: practice
 datasource:
  url: jdbc:postgresql://localhost:1331/postgres
  username: postgres
  password: navneet
  driverClassName: org.postgresql.Driver 
 security:
  user:
   name: user
   password: pass 